// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsPMWgytETWNg1l4RQOko46ZyjjjXbxQw',
    appId: '1:292978153429:web:f5d26d885e658e85ab0f5c',
    messagingSenderId: '292978153429',
    projectId: 'firebase-fm',
    authDomain: 'fir-fm-84a85.firebaseapp.com',
    storageBucket: 'firebase-fm.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKe6EjSiouADhA6G2ZWWke83YPE1ahLi8',
    appId: '1:292978153429:android:ec9882985139fa94ab0f5c',
    messagingSenderId: '292978153429',
    projectId: 'firebase-fm',
    storageBucket: 'firebase-fm.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHhvgubN8n7CC1MjAUnj7EBv6n2YdZ4SU',
    appId: '1:292978153429:ios:6c46daaf72fa943dab0f5c',
    messagingSenderId: '292978153429',
    projectId: 'firebase-fm',
    storageBucket: 'firebase-fm.appspot.com',
    iosClientId: '292978153429-7dhtadlejli10g6jt1msisu5ve9f3ov1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHhvgubN8n7CC1MjAUnj7EBv6n2YdZ4SU',
    appId: '1:292978153429:ios:6c5dcecd105d3d14ab0f5c',
    messagingSenderId: '292978153429',
    projectId: 'firebase-fm',
    storageBucket: 'firebase-fm.appspot.com',
    iosClientId: '292978153429-v6kehsd0p0ms1gftmtioboppul2s31em.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfm.RunnerTests',
  );
}
